### ISSUE TITLE
Authorization failed or requested resource not found

### ISSUE THREAD

**Issue by nasr18** [scotti-fletcher/oci-letsencrypt#1]
Hi @scotti-fletcher 

To begin with, thank you for coming up with this project.

I just followed your article to automate LE certificate renewal process. When I invoke the OCI function, I'm getting `Authorization failed or requested resource not found`. Really appreciate your help if you help me to overcome this issue.

**Comment by nasr18** [comment]
this is the error from fn cli

`{"code":"FunctionInvokeExecutionFailed","message":"function failed"}
Error invoking function. status: 502 message: function failed`

OCI Functions Troubleshooting page saying that this error will occur if you have bugs in your code.

**Comment by scotti-fletcher** [comment]
Hi @nasr18. A 502 can occur for a number of reasons, it's not specifically code related. I recently deployed this solution so I know it works. Your first message indicates it's likely a dynamic-group and/or policy issue. My suggestion is to look at audit logs. This will tell you if there's API calls that are failing. 

Alternatively if you want to look at a different set of instructions and a video you can find those under "Tech Day 2023" here https://techdays.withoracle.cloud/

**Comment by nasr18** [comment]
Thank you @scotti-fletcher for replying.

I just copied and pasted your policy and in dynamic-group gave my compartment id.

Don't know what I'm missing here.

**Comment by scotti-fletcher** [comment]
Just to make sure you're following the right instructions, you're using these https://redthunder.blog/2022/10/14/managing-multiple-lets-encrypt-certificates-with-oracle-cloud-infrastructure/ and have two functions in your Application?

Have you enabled the function invocation logs? There should be more info in there.

**Comment by nasr18** [comment]
I'm following this article https://medium.com/@scotti.fletcher.1/managing-multiple-lets-encrypt-certificates-with-oracle-cloud-infrastructure-470eef51630

I could see both `lets-encrypt` and `worker` functions, and also enabled function invocation logs.

![image](https://github.com/scotti-fletcher/oci-letsencrypt/assets/7514936/14577b17-282a-43c3-8873-9dc9cea61737)


getting `Authorization failed or requested resource not found` when calling `functions_client.list_functions` method.

**Comment by nasr18** [comment]
I guess solved the policy issue after changing `to use fn-invokation` to `to use functions-family`.

Now I'm getting this error message.... `"unknown keywords: :id, :displayName, :applicationId, :compartmentId, :lifecycleState, :image, :imageDigest, :memoryInMBs, :timeoutInSeconds, :traceConfig, :freeformTags, :invokeEndpoint, :definedTags, :timeCreated, :timeUpdated"`

**Comment by scotti-fletcher** [comment]
That looks like an error to do with the functions not being recognised.
Although I’ve never seen that error before. Is it in the invocation logs
too? Is that for the worker function?

**Comment by nasr18** [comment]
yes, it's in the invocation logs.

When executing this line, `worker = functions_client.list_functions(ENV['FN_APP_ID'], display_name: 'worker').data.first` getting above-mentioned error.

**Comment by scotti-fletcher** [comment]
Ok, have you set the FN_APP_ID configuration variable to the OCID of the
function? And there's a second function in there called worker?

**Comment by nasr18** [comment]
Yes, 2nd function 'worker' is there.

After removing `.first` from `worker = functions_client.list_functins(ENV['FN_APP_ID'], display_name: 'worker').data.first` execution moved further and then got stuck at `invoke_client = OCI::Functions::FunctionsInvokeClient.new(signer: get_signer, endpoint: worker.invoke_endpoint)` with error message saying `undefined method 'invoke_endpoint'`.

**Comment by scotti-fletcher** [comment]
That is to be expected. If worker is not retrieved, then worker.invoke_endpoint will be not set. 
It appears something at or before the list_functions is not working. 

If you're still having trouble I'm happy to jump on a call with you to debug.

**Comment by nasr18** [comment]
output of this line `worker = functions_client.list_functions(ENV['FN_APP_ID'], display_name: 'worker').data` is

 ```"{:id=>\"ocid1.fnfunc.oc1.ap-hyderabad-1.aaaaaaaahcdn3zyq6zyqjryobqwm5qobxoij6lbzxhfkysfc52xsciaitwka\", :displayName=>\"worker\", :applicationId=>\"ocid1.fnapp.oc1.ap-hyderabad-1.aaaaaaaashz7ld6dkfdc5o7e77jicgi5ed2jqfaxd5jka3q325muu6v7uuha\", :compartmentId=>\"ocid1.compartment.oc1..aaaaaaaadm7ttydfupn2g5qt7flt2dskvczzqgjm7edp5sbac4btxbzu2kiq\", :lifecycleState=>\"ACTIVE\", :image=>\"hyd.ocir.io/axihai20tgzq/acme-certbot/worker:1.0.4\", :imageDigest=>\"sha256:659da6484d735a958995968a6721eed911ccbb99319688184f647ee2cc884d59\", :memoryInMBs=>1024, :timeoutInSeconds=>300, :traceConfig=>{:isEnabled=>false}, :freeformTags=>{}, :invokeEndpoint=>\"https://5muu6v7uuha.ap-hyderabad-1.functions.oci.oraclecloud.com\", :definedTags=>{\"Oracle-Tags\"=>{\"CreatedBy\"=>\"default/nasrullah\", \"CreatedOn\"=>\"2023-06-12T06:10:06.534Z\"}}, :timeCreated=>#<DateTime: 2023-06-12T06:10:06+00:00 ((2460108j,22206s,657000000n),+0s,2299161j)>, :timeUpdated=>#<DateTime: 2023-06-12T06:10:06+00:00 ((2460108j,22206s,657000000n),+0s,2299161j)>}"```

and type of above output is `Array`

**Comment by nasr18** [comment]
OMG.... finally... made it to work. I hard-coded worker's id and invoke_endpoint to make it work.
